; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S < %s -p loop-vectorize -force-vector-width=4 -enable-check-first-vectorization | FileCheck %s

; Nested (guarded) early exits for check-first vectorization. The guard predicate
; is AND-combined into the guarded exit condition: for a single guard the check
; is any_of(guard AND exit_cond); for two nested guards it is
; any_of(g0 AND g1 AND exit_cond). All guard/condition loads are proven
; dereferenceable for the whole trip count, so they are widened unconditionally
; and the guard is applied to the condition (not the load).

@A = global [1024 x i32] zeroinitializer
@B = global [1024 x i32] zeroinitializer
@C = global [1024 x i32] zeroinitializer
@D = global [1024 x i32] zeroinitializer

; for (i) { if (A[i] != 0) { if (B[i] == 0) return i; } D[i] = A[i]; }
define i32 @single_guard() {
; CHECK-LABEL: define i32 @single_guard() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY3:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 3
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [1024 x i32], ptr @A, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ne <4 x i32> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [1024 x i32], ptr @B, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i32>, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq <4 x i32> [[WIDE_LOAD2]], zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = select <4 x i1> [[TMP4]], <4 x i1> [[TMP6]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = freeze <4 x i1> [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP8]])
; CHECK-NEXT:    br i1 [[TMP9]], label %[[VECTOR_CHECK_EXIT:.*]], label %[[VECTOR_BODY3]]
; CHECK:       [[VECTOR_BODY3]]:
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP2]]
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    store i32 [[TMP14]], ptr [[TMP10]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 2
; CHECK-NEXT:    store i32 [[TMP16]], ptr [[TMP12]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 3
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[TMP13]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP18]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[RET_N:.*]]
; CHECK:       [[VECTOR_CHECK_EXIT]]:
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP7]], i1 false)
; CHECK-NEXT:    [[MASKED_REPLAY_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 0, i64 [[FIRST_ACTIVE_LANE]])
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 0
; CHECK-NEXT:    br i1 [[TMP19]], label %[[PRED_STORE_IF:.*]], label %[[SCALAR_PH:.*]]
; CHECK:       [[PRED_STORE_IF]]:
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[TMP21:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    store i32 [[TMP21]], ptr [[TMP20]], align 4
; CHECK-NEXT:    br label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[TMP25:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 1
; CHECK-NEXT:    br i1 [[TMP25]], label %[[PRED_STORE_IF4:.*]], label %[[FOR_BODY:.*]]
; CHECK:       [[PRED_STORE_IF4]]:
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    store i32 [[TMP24]], ptr [[TMP23]], align 4
; CHECK-NEXT:    br label %[[FOR_BODY]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[XG:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 2
; CHECK-NEXT:    br i1 [[XG]], label %[[GUARD:.*]], label %[[LATCH:.*]]
; CHECK:       [[GUARD]]:
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[TMP27:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 2
; CHECK-NEXT:    store i32 [[TMP27]], ptr [[TMP29]], align 4
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[TMP28:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 3
; CHECK-NEXT:    br i1 [[TMP28]], label %[[PRED_STORE_IF8:.*]], label %[[EXIT0:.*]]
; CHECK:       [[PRED_STORE_IF8]]:
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP2]]
; CHECK-NEXT:    [[TMP26:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 3
; CHECK-NEXT:    store i32 [[TMP26]], ptr [[TMP22]], align 4
; CHECK-NEXT:    br label %[[EXIT0]]
; CHECK:       [[EXIT0]]:
; CHECK-NEXT:    [[IV_LCSSA:%.*]] = add nuw i64 [[INDEX]], [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    [[T0:%.*]] = trunc i64 [[IV_LCSSA]] to i32
; CHECK-NEXT:    br label %[[RET:.*]]
; CHECK:       [[RET_N]]:
; CHECK-NEXT:    br label %[[RET]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ [[T0]], %[[EXIT1]] ], [ 1024, %[[RET_N]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %ga = getelementptr inbounds [1024 x i32], ptr @A, i64 0, i64 %iv
  %la = load i32, ptr %ga, align 4
  %xg = icmp ne i32 %la, 0
  br i1 %xg, label %guard, label %latch

guard:
  %gb = getelementptr inbounds [1024 x i32], ptr @B, i64 0, i64 %iv
  %lb = load i32, ptr %gb, align 4
  %yb = icmp eq i32 %lb, 0
  br i1 %yb, label %exit0, label %latch

latch:
  %gd = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 %iv
  store i32 %la, ptr %gd, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %done = icmp eq i64 %iv.next, 1024
  br i1 %done, label %ret.n, label %for.body

exit0:
  %t0 = trunc i64 %iv to i32
  br label %ret

ret.n:
  br label %ret

ret:
  %r = phi i32 [ %t0, %exit0 ], [ 1024, %ret.n ]
  ret i32 %r
}

; for (i) { if (A[i]!=0) { if (C[i]!=0) { if (B[i]==0) return i; } } D[i]=A[i]; }
define i32 @two_nested_guards() {
; CHECK-LABEL: define i32 @two_nested_guards() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY4:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 3
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [1024 x i32], ptr @A, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ne <4 x i32> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [1024 x i32], ptr @C, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i32>, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ne <4 x i32> [[WIDE_LOAD2]], zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds [1024 x i32], ptr @B, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i32>, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq <4 x i32> [[WIDE_LOAD3]], zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = select <4 x i1> [[TMP4]], <4 x i1> [[TMP6]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = select <4 x i1> [[TMP9]], <4 x i1> [[TMP8]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP11:%.*]] = freeze <4 x i1> [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP11]])
; CHECK-NEXT:    br i1 [[TMP12]], label %[[VECTOR_CHECK_EXIT:.*]], label %[[VECTOR_BODY4]]
; CHECK:       [[VECTOR_BODY4]]:
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP2]]
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[TMP13]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    store i32 [[TMP18]], ptr [[TMP14]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 2
; CHECK-NEXT:    store i32 [[TMP19]], ptr [[TMP15]], align 4
; CHECK-NEXT:    [[TMP20:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 3
; CHECK-NEXT:    store i32 [[TMP20]], ptr [[TMP16]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP21:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP21]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[VECTOR_CHECK_EXIT]]:
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP10]], i1 false)
; CHECK-NEXT:    [[MASKED_REPLAY_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 0, i64 [[FIRST_ACTIVE_LANE]])
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 0
; CHECK-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF:.*]], label %[[FOR_BODY:.*]]
; CHECK:       [[PRED_STORE_IF]]:
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    store i32 [[TMP24]], ptr [[TMP23]], align 4
; CHECK-NEXT:    br label %[[FOR_BODY]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[XG:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 1
; CHECK-NEXT:    br i1 [[XG]], label %[[G1:.*]], label %[[LATCH:.*]]
; CHECK:       [[G1]]:
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP27:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    store i32 [[TMP27]], ptr [[TMP26]], align 4
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[TMP28:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 2
; CHECK-NEXT:    br i1 [[TMP28]], label %[[PRED_STORE_IF7:.*]], label %[[PRED_STORE_CONTINUE8:.*]]
; CHECK:       [[PRED_STORE_IF7]]:
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[TMP30:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 2
; CHECK-NEXT:    store i32 [[TMP30]], ptr [[TMP32]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE8]]
; CHECK:       [[PRED_STORE_CONTINUE8]]:
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <4 x i1> [[MASKED_REPLAY_MASK]], i64 3
; CHECK-NEXT:    br i1 [[TMP31]], label %[[PRED_STORE_IF9:.*]], label %[[EXIT0:.*]]
; CHECK:       [[PRED_STORE_IF9]]:
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 [[TMP2]]
; CHECK-NEXT:    [[TMP29:%.*]] = extractelement <4 x i32> [[WIDE_LOAD]], i64 3
; CHECK-NEXT:    store i32 [[TMP29]], ptr [[TMP25]], align 4
; CHECK-NEXT:    br label %[[EXIT0]]
; CHECK:       [[EXIT0]]:
; CHECK-NEXT:    [[IV_LCSSA:%.*]] = add nuw i64 [[INDEX]], [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    [[T0:%.*]] = trunc i64 [[IV_LCSSA]] to i32
; CHECK-NEXT:    br label %[[RET:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[RET]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ [[T0]], %[[EXIT1]] ], [ 1024, %[[SCALAR_PH]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %ga = getelementptr inbounds [1024 x i32], ptr @A, i64 0, i64 %iv
  %la = load i32, ptr %ga, align 4
  %xg = icmp ne i32 %la, 0
  br i1 %xg, label %g1, label %latch

g1:
  %gc = getelementptr inbounds [1024 x i32], ptr @C, i64 0, i64 %iv
  %lc = load i32, ptr %gc, align 4
  %zg = icmp ne i32 %lc, 0
  br i1 %zg, label %g2, label %latch

g2:
  %gb = getelementptr inbounds [1024 x i32], ptr @B, i64 0, i64 %iv
  %lb = load i32, ptr %gb, align 4
  %yb = icmp eq i32 %lb, 0
  br i1 %yb, label %exit0, label %latch

latch:
  %gd = getelementptr inbounds [1024 x i32], ptr @D, i64 0, i64 %iv
  store i32 %la, ptr %gd, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %done = icmp eq i64 %iv.next, 1024
  br i1 %done, label %ret.n, label %for.body

exit0:
  %t0 = trunc i64 %iv to i32
  br label %ret

ret.n:
  br label %ret

ret:
  %r = phi i32 [ %t0, %exit0 ], [ 1024, %ret.n ]
  ret i32 %r
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
;.
